CREATE TABLE books(
   author   VARCHAR(26) NOT NULL
  ,country  VARCHAR(32) NOT NULL
  ,language VARCHAR(15) NOT NULL
  ,link     VARCHAR(82)
  ,pages    INTEGER  NOT NULL
  ,title    VARCHAR(47) NOT NULL
  ,year     INTEGER  NOT NULL
  ,id       INTEGER  NOT NULL PRIMARY KEY 
);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Chinua Achebe','Nigeria','English','https://en.wikipedia.org/wiki/Things_Fall_Apart',209,'Things Fall Apart',1958,0);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Hans Christian Andersen','Denmark','Danish','https://en.wikipedia.org/wiki/Fairy_Tales_Told_for_Children._First_Collection.',784,'Fairy tales',1836,1);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Dante Alighieri','Italy','Italian','https://en.wikipedia.org/wiki/Divine_Comedy',928,'The Divine Comedy',1315,2);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Unknown','Sumer and Akkadian Empire','Akkadian','https://en.wikipedia.org/wiki/Epic_of_Gilgamesh',160,'The Epic Of Gilgamesh',-1700,3);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Unknown','Achaemenid Empire','Hebrew','https://en.wikipedia.org/wiki/Book_of_Job',176,'The Book Of Job',-600,4);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Unknown','India/Iran/Iraq/Egypt/Tajikistan','Arabic','https://en.wikipedia.org/wiki/One_Thousand_and_One_Nights',288,'One Thousand and One Nights',1200,5);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Unknown','Iceland','Old Norse','https://en.wikipedia.org/wiki/Nj%C3%A1ls_saga',384,'Njál''s Saga',1350,6);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Jane Austen','United Kingdom','English','https://en.wikipedia.org/wiki/Pride_and_Prejudice',226,'Pride and Prejudice',1813,7);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Honoré de Balzac','France','French','https://en.wikipedia.org/wiki/Le_P%C3%A8re_Goriot',443,'Le Père Goriot',1835,8);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Samuel Beckett','Republic of Ireland','French, English','https://en.wikipedia.org/wiki/Molloy_(novel)',256,'Molloy, Malone Dies, The Unnamable, the trilogy',1952,9);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Giovanni Boccaccio','Italy','Italian','https://en.wikipedia.org/wiki/The_Decameron',1024,'The Decameron',1351,10);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Jorge Luis Borges','Argentina','Spanish','https://en.wikipedia.org/wiki/Ficciones',224,'Ficciones',1965,11);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Emily Brontë','United Kingdom','English','https://en.wikipedia.org/wiki/Wuthering_Heights',342,'Wuthering Heights',1847,12);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Albert Camus','Algeria, French Empire','French','https://en.wikipedia.org/wiki/The_Stranger_(novel)',185,'The Stranger',1942,13);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Paul Celan','Romania, France','German',NULL,320,'Poems',1952,14);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Louis-Ferdinand Céline','France','French','https://en.wikipedia.org/wiki/Journey_to_the_End_of_the_Night',505,'Journey to the End of the Night',1932,15);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Miguel de Cervantes','Spain','Spanish','https://en.wikipedia.org/wiki/Don_Quixote',1056,'Don Quijote De La Mancha',1610,16);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Geoffrey Chaucer','England','English','https://en.wikipedia.org/wiki/The_Canterbury_Tales',544,'The Canterbury Tales',1450,17);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Anton Chekhov','Russia','Russian','https://en.wikipedia.org/wiki/List_of_short_stories_by_Anton_Chekhov',194,'Stories',1886,18);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Joseph Conrad','United Kingdom','English','https://en.wikipedia.org/wiki/Nostromo',320,'Nostromo',1904,19);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Charles Dickens','United Kingdom','English','https://en.wikipedia.org/wiki/Great_Expectations',194,'Great Expectations',1861,20);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Denis Diderot','France','French','https://en.wikipedia.org/wiki/Jacques_the_Fatalist',596,'Jacques the Fatalist',1796,21);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Alfred Döblin','Germany','German','https://en.wikipedia.org/wiki/Berlin_Alexanderplatz',600,'Berlin Alexanderplatz',1929,22);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Fyodor Dostoevsky','Russia','Russian','https://en.wikipedia.org/wiki/Crime_and_Punishment',551,'Crime and Punishment',1866,23);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Fyodor Dostoevsky','Russia','Russian','https://en.wikipedia.org/wiki/The_Idiot',656,'The Idiot',1869,24);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Fyodor Dostoevsky','Russia','Russian','https://en.wikipedia.org/wiki/Demons_(Dostoyevsky_novel)',768,'The Possessed',1872,25);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Fyodor Dostoevsky','Russia','Russian','https://en.wikipedia.org/wiki/The_Brothers_Karamazov',824,'The Brothers Karamazov',1880,26);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('George Eliot','United Kingdom','English','https://en.wikipedia.org/wiki/Middlemarch',800,'Middlemarch',1871,27);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Ralph Ellison','United States','English','https://en.wikipedia.org/wiki/Invisible_Man',581,'Invisible Man',1952,28);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Euripides','Greece','Greek','https://en.wikipedia.org/wiki/Medea_(play)',104,'Medea',-431,29);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('William Faulkner','United States','English','https://en.wikipedia.org/wiki/Absalom,_Absalom!',313,'Absalom, Absalom!',1936,30);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('William Faulkner','United States','English','https://en.wikipedia.org/wiki/The_Sound_and_the_Fury',326,'The Sound and the Fury',1929,31);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Gustave Flaubert','France','French','https://en.wikipedia.org/wiki/Madame_Bovary',528,'Madame Bovary',1857,32);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Gustave Flaubert','France','French','https://en.wikipedia.org/wiki/Sentimental_Education',606,'Sentimental Education',1869,33);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Federico García Lorca','Spain','Spanish','https://en.wikipedia.org/wiki/Gypsy_Ballads',218,'Gypsy Ballads',1928,34);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Gabriel García Márquez','Colombia','Spanish','https://en.wikipedia.org/wiki/One_Hundred_Years_of_Solitude',417,'One Hundred Years of Solitude',1967,35);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Gabriel García Márquez','Colombia','Spanish','https://en.wikipedia.org/wiki/Love_in_the_Time_of_Cholera',368,'Love in the Time of Cholera',1985,36);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Johann Wolfgang von Goethe','Saxe-Weimar','German','https://en.wikipedia.org/wiki/Goethe%27s_Faust',158,'Faust',1832,37);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Nikolai Gogol','Russia','Russian','https://en.wikipedia.org/wiki/Dead_Souls',432,'Dead Souls',1842,38);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Günter Grass','Germany','German','https://en.wikipedia.org/wiki/The_Tin_Drum',600,'The Tin Drum',1959,39);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('João Guimarães Rosa','Brazil','Portuguese','https://en.wikipedia.org/wiki/The_Devil_to_Pay_in_the_Backlands',494,'The Devil to Pay in the Backlands',1956,40);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Knut Hamsun','Norway','Norwegian','https://en.wikipedia.org/wiki/Hunger_(Hamsun_novel)',176,'Hunger',1890,41);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Ernest Hemingway','United States','English','https://en.wikipedia.org/wiki/The_Old_Man_and_the_Sea',128,'The Old Man and the Sea',1952,42);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Homer','Greece','Greek','https://en.wikipedia.org/wiki/Iliad',608,'Iliad',-735,43);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Homer','Greece','Greek','https://en.wikipedia.org/wiki/Odyssey',374,'Odyssey',-800,44);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Henrik Ibsen','Norway','Norwegian','https://en.wikipedia.org/wiki/A_Doll%27s_House',68,'A Doll''s House',1879,45);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('James Joyce','Irish Free State','English','https://en.wikipedia.org/wiki/Ulysses_(novel)',228,'Ulysses',1922,46);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Franz Kafka','Czechoslovakia','German','https://en.wikipedia.org/wiki/Franz_Kafka_bibliography#Short_stories',488,'Stories',1924,47);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Franz Kafka','Czechoslovakia','German','https://en.wikipedia.org/wiki/The_Trial',160,'The Trial',1925,48);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Franz Kafka','Czechoslovakia','German','https://en.wikipedia.org/wiki/The_Castle_(novel)',352,'The Castle',1926,49);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Kālidāsa','India','Sanskrit','https://en.wikipedia.org/wiki/Abhij%C3%B1%C4%81na%C5%9B%C4%81kuntalam',147,'The recognition of Shakuntala',150,50);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Yasunari Kawabata','Japan','Japanese','https://en.wikipedia.org/wiki/The_Sound_of_the_Mountain',288,'The Sound of the Mountain',1954,51);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Nikos Kazantzakis','Greece','Greek','https://en.wikipedia.org/wiki/Zorba_the_Greek',368,'Zorba the Greek',1946,52);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('D. H. Lawrence','United Kingdom','English','https://en.wikipedia.org/wiki/Sons_and_Lovers',432,'Sons and Lovers',1913,53);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Halldór Laxness','Iceland','Icelandic','https://en.wikipedia.org/wiki/Independent_People',470,'Independent People',1934,54);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Giacomo Leopardi','Italy','Italian',NULL,184,'Poems',1818,55);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Doris Lessing','United Kingdom','English','https://en.wikipedia.org/wiki/The_Golden_Notebook',688,'The Golden Notebook',1962,56);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Astrid Lindgren','Sweden','Swedish','https://en.wikipedia.org/wiki/Pippi_Longstocking',160,'Pippi Longstocking',1945,57);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Lu Xun','China','Chinese','https://en.wikipedia.org/wiki/A_Madman%27s_Diary',389,'Diary of a Madman',1918,58);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Naguib Mahfouz','Egypt','Arabic','https://en.wikipedia.org/wiki/Children_of_Gebelawi',355,'Children of Gebelawi',1959,59);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Thomas Mann','Germany','German','https://en.wikipedia.org/wiki/Buddenbrooks',736,'Buddenbrooks',1901,60);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Thomas Mann','Germany','German','https://en.wikipedia.org/wiki/The_Magic_Mountain',720,'The Magic Mountain',1924,61);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Herman Melville','United States','English','https://en.wikipedia.org/wiki/Moby-Dick',378,'Moby Dick',1851,62);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Michel de Montaigne','France','French','https://en.wikipedia.org/wiki/Essays_(Montaigne)',404,'Essays',1595,63);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Elsa Morante','Italy','Italian','https://en.wikipedia.org/wiki/History_(novel)',600,'History',1974,64);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Toni Morrison','United States','English','https://en.wikipedia.org/wiki/Beloved_(novel)',321,'Beloved',1987,65);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Murasaki Shikibu','Japan','Japanese','https://en.wikipedia.org/wiki/The_Tale_of_Genji',1360,'The Tale of Genji',1006,66);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Robert Musil','Austria','German','https://en.wikipedia.org/wiki/The_Man_Without_Qualities',365,'The Man Without Qualities',1931,67);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Vladimir Nabokov','Russia/United States','English','https://en.wikipedia.org/wiki/Lolita',317,'Lolita',1955,68);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('George Orwell','United Kingdom','English','https://en.wikipedia.org/wiki/Nineteen_Eighty-Four',272,'Nineteen Eighty-Four',1949,69);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Ovid','Roman Empire','Classical Latin','https://en.wikipedia.org/wiki/Metamorphoses',576,'Metamorphoses',100,70);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Fernando Pessoa','Portugal','Portuguese','https://en.wikipedia.org/wiki/The_Book_of_Disquiet',272,'The Book of Disquiet',1928,71);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Edgar Allan Poe','United States','English','https://en.wikipedia.org/wiki/Edgar_Allan_Poe_bibliography#Tales',842,'Tales',1950,72);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Marcel Proust','France','French','https://en.wikipedia.org/wiki/In_Search_of_Lost_Time',2408,'In Search of Lost Time',1920,73);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('François Rabelais','France','French','https://en.wikipedia.org/wiki/Gargantua_and_Pantagruel',623,'Gargantua and Pantagruel',1533,74);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Juan Rulfo','Mexico','Spanish','https://en.wikipedia.org/wiki/Pedro_P%C3%A1ramo',124,'Pedro Páramo',1955,75);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Rumi','Sultanate of Rum','Persian','https://en.wikipedia.org/wiki/Masnavi',438,'The Masnavi',1236,76);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Salman Rushdie','United Kingdom, India','English','https://en.wikipedia.org/wiki/Midnight%27s_Children',536,'Midnight''s Children',1981,77);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Saadi','Persia, Persian Empire','Persian','https://en.wikipedia.org/wiki/Bustan_(book)',298,'Bostan',1257,78);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Tayeb Salih','Sudan','Arabic','https://en.wikipedia.org/wiki/Season_of_Migration_to_the_North',139,'Season of Migration to the North',1966,79);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('José Saramago','Portugal','Portuguese','https://en.wikipedia.org/wiki/Blindness_(novel)',352,'Blindness',1995,80);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('William Shakespeare','England','English','https://en.wikipedia.org/wiki/Hamlet',432,'Hamlet',1603,81);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('William Shakespeare','England','English','https://en.wikipedia.org/wiki/King_Lear',384,'King Lear',1608,82);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('William Shakespeare','England','English','https://en.wikipedia.org/wiki/Othello',314,'Othello',1609,83);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Sophocles','Greece','Greek','https://en.wikipedia.org/wiki/Oedipus_the_King',88,'Oedipus the King',-430,84);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Stendhal','France','French','https://en.wikipedia.org/wiki/The_Red_and_the_Black',576,'The Red and the Black',1830,85);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Laurence Sterne','England','English','https://en.wikipedia.org/wiki/The_Life_and_Opinions_of_Tristram_Shandy,_Gentleman',640,'The Life And Opinions of Tristram Shandy',1760,86);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Italo Svevo','Italy','Italian','https://en.wikipedia.org/wiki/Zeno%27s_Conscience',412,'Confessions of Zeno',1923,87);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Jonathan Swift','Ireland','English','https://en.wikipedia.org/wiki/Gulliver%27s_Travels',178,'Gulliver''s Travels',1726,88);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Leo Tolstoy','Russia','Russian','https://en.wikipedia.org/wiki/War_and_Peace',1296,'War and Peace',1867,89);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Leo Tolstoy','Russia','Russian','https://en.wikipedia.org/wiki/Anna_Karenina',864,'Anna Karenina',1877,90);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Leo Tolstoy','Russia','Russian','https://en.wikipedia.org/wiki/The_Death_of_Ivan_Ilyich',92,'The Death of Ivan Ilyich',1886,91);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Mark Twain','United States','English','https://en.wikipedia.org/wiki/Adventures_of_Huckleberry_Finn',224,'The Adventures of Huckleberry Finn',1884,92);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Valmiki','India','Sanskrit','https://en.wikipedia.org/wiki/Ramayana',152,'Ramayana',-450,93);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Virgil','Roman Empire','Classical Latin','https://en.wikipedia.org/wiki/Aeneid',442,'The Aeneid',-23,94);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Vyasa','India','Sanskrit','https://en.wikipedia.org/wiki/Mahabharata',276,'Mahabharata',-700,95);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Walt Whitman','United States','English','https://en.wikipedia.org/wiki/Leaves_of_Grass',152,'Leaves of Grass',1855,96);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Virginia Woolf','United Kingdom','English','https://en.wikipedia.org/wiki/Mrs_Dalloway',216,'Mrs Dalloway',1925,97);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Virginia Woolf','United Kingdom','English','https://en.wikipedia.org/wiki/To_the_Lighthouse',209,'To the Lighthouse',1927,98);
INSERT INTO books(author,country,language,link,pages,title,year,id) VALUES ('Marguerite Yourcenar','France/Belgium','French','https://en.wikipedia.org/wiki/Memoirs_of_Hadrian',408,'Memoirs of Hadrian',1951,99);
